package com.tdesi.sa_sistema_de_biblioteca.model;


public enum EditoraLivro {
    
    // Editoras Brasileiras
    COMPANHIA_DAS_LETRAS("Companhia das Letras"),
    RECORD("Editora Record"),
    ROCCO("Editora Rocco"),
    GLOBO_LIVROS("Globo Livros"),
    SARAIVA("Saraiva"),
    MODERNA("Moderna"),
    ATICA("Ática"),
    FTD("FTD Educação"),
    PAULUS("Paulus"),
    NOVO_CONCEITO("Novo Conceito"),
    SEGUINTE("Seguinte"),
    ARQUEIRO("Arqueiro"),
    INTRINSECA("Intrínseca"),
    ZAHAR("Zahar"),
    NOVA_FRONTEIRA("Nova Fronteira"),
    PLANETA_DO_BRASIL("Planeta do Brasil"),
    DARKSIDE("DarkSide Books"),
    AUTENTICA("Autêntica"),
    LPM("L&PM Editores"),
    GENERALE("Generale"),
    PENSAMENTO("Pensamento"),
    VOZES("Editora Vozes"),
    SUMA("Suma de Letras"),
    BERTRAND_BRASIL("Bertrand Brasil"),
    MARTINS_FONTES("Martins Fontes"),
    EDITORA_34("Editora 34"),
    CULTRIX("Cultrix"),
    EDICOES_SM("Edições SM"),
    MELHORAMENTOS("Melhoramentos"),
    GIZ_EDITORIAL("Giz Editorial"),
    NOVO_SECULO("Novo Século"),
    GRUPO_A("Grupo A"),
    GRUPO_GEN("Grupo GEN"),
    PUBLIFOLHA("Publifolha"),
    MANOLE("Manole"),
    INTERSABERES("Intersaberes"),
    ESCALA("Editora Escala"),
    LAFONTE("Lafonte"),
    UNIVERSO_DOS_LIVROS("Universo dos Livros"),
    QUADRANTE("Editora Quadrante"),
    HEDRA("Hedra"),
    DCL("DCL"),
    CARAMURE("Caramurê Publicações"),
    COBOGO("Cobogó"),
    LITERARTE("Literarte"),
    LITERARTE_ACADEMIA("Literarte Academia"),
    ALL_PRINT("All Print"),
    ALTA_BOOKS("Alta Books"),
    ALEPH("Editora Aleph"),
    DRACO("Editora Draco"),
    EVIDENCIA("Evidência Editora"),
    
    // Editoras Internacionais
    PENGUIN_RANDOM_HOUSE("Penguin Random House"),
    HARPERCOLLINS("HarperCollins"),
    SIMON_AND_SCHUSTER("Simon & Schuster"),
    HACHETTE_BOOK_GROUP("Hachette Book Group"),
    MACMILLAN_PUBLISHERS("Macmillan Publishers"),
    SCHOLASTIC("Scholastic"),
    OXFORD_UNIVERSITY_PRESS("Oxford University Press"),
    CAMBRIDGE_UNIVERSITY_PRESS("Cambridge University Press"),
    WILEY("Wiley"),
    PEARSON("Pearson"),
    HARLEQUIN("Harlequin"),
    TOR_BOOKS("Tor Books"),
    KNOPF_DOUBLEDAY("Knopf Doubleday"),
    VINTAGE_BOOKS("Vintage Books"),
    ST_MARTINS_PRESS("St. Martin's Press"),
    LITTLE_BROWN("Little, Brown and Company"),
    BLOOMSBURY("Bloomsbury"),
    PAN_MACMILLAN("Pan Macmillan"),
    THAMES_AND_HUDSON("Thames & Hudson"),
    FSG("Farrar, Straus and Giroux"),
    DORLING_KINDERSLEY("Dorling Kindersley"),
    KENSINGTON_PUBLISHING("Kensington Publishing"),
    BLACKWELL_PUBLISHING("Blackwell Publishing"),
    TAYLOR_AND_FRANCIS("Taylor & Francis"),
    SPRINGER("Springer"),
    ELSEVIER("Elsevier"),
    MIT_PRESS("MIT Press"),
    NORTON("W. W. Norton & Company"),
    GROVE_PRESS("Grove Press"),
    NEW_PRESS("The New Press"),
    HARVARD_UNIVERSITY_PRESS("Harvard University Press"),
    YALE_UNIVERSITY_PRESS("Yale University Press"),
    PRINCETON_UNIVERSITY_PRESS("Princeton University Press"),
    MARVEL_COMICS("Marvel Comics"),
    DC_COMICS("DC Comics"),
    IMAGE_COMICS("Image Comics"),
    CHRONICLE_BOOKS("Chronicle Books"),
    TITAN_BOOKS("Titan Books"),
    MELVILLE_HOUSE("Melville House"),
    VERSO_BOOKS("Verso Books"),
    BEACON_PRESS("Beacon Press"),
    BASIC_BOOKS("Basic Books"),
    AVON_BOOKS("Avon Books"),
    TOR_FORGE("Tor/Forge"),
    FANTAGRAPHICS("Fantagraphics Books"),
    NEW_DIRECTIONS("New Directions"),
    PUSHKIN_PRESS("Pushkin Press"),
    ATLANTIC_BOOKS("Atlantic Books");

    private final String nomeAmigavel;

    EditoraLivro(String nomeAmigavel) {
        this.nomeAmigavel = nomeAmigavel;
    }

    public String getNomeAmigavel() {
        return nomeAmigavel;
    }
}
